class BatteryControl:
    BAT__STORAGE_MODE = 0xB0
    BAT__TEMPERATURE = 0xB1
    BAT__VOLTAGE = 0xB2
    BAT__CURRENT = 0xB3
    BAT__RSOC = 0xB4
    BAT__TIME_TO_EMPTY = 0xB5
    BAT__TIME_TO_FULL = 0xB6
    BAT__VOLT_CELL1 = 0xB7
    BAT__VOLT_CELL2 = 0xB8
    BAT__VOLT_CELL3 = 0xB9
    BAT__VOLT_CELL4 = 0xBA
    BAT__PF_ERROR = 0xBB
    BAT__SERIAL_NUM = 0xBC
    BAT__MANUF_DATE = 0xBD
    BAT__CHARGING_ERROR = 0xBF
