class PowerControl:
    PWR__SHUTDOWN_CTRL = 0xA0
    PWR__BUTT_SHORT_HOLD_TURNON = 0xA1
    PWR__BUTT_SHORT_HOLD_TURNOFF = 0xA2
    PWR__BUTT_LONG_HOLD = 0xA3
    PWR__M1_TIMEOUT_MIN = 0xAA
    PWR__M1_TIMEOUT_MAX = 0xAB
    PWR__M2_TIMEOUT_MIN = 0xAC
    PWR__M2_TIMEOUT_MAX = 0xAD
    PWR__M3_TIMEOUT = 0xAE


class ShutdownRegister:
    # Bits
    PWR__SHUTDOWN_CTRL__HELD = 0x1
    PWR__SHUTDOWN_CTRL__BUTT = 0x2
    PWR__SHUTDOWN_CTRL__MODE = 0x18
    PWR__SHUTDOWN_CTRL__AC = 0x40
    PWR__SHUTDOWN_CTRL__CANCEL = 0x80
