#!/bin/bash -e

/usr/lib/pt-device-manager/config/xhost-setup


echo "Unmasking device manager service..."
systemctl unmask pt-device-manager

echo "Unmasking OLED animation service..."
systemctl unmask pt-oled-startup-anim


echo "Enabling device manager service..."
systemctl enable pt-device-manager

echo "Enabling OLED animation service..."
systemctl enable pt-oled-startup-anim


echo "Starting device manager service..."
systemctl start pt-device-manager
