#!/bin/bash -e

echo "Disabling xscreensaver"
xscreensaverConfigs=()
for D in $(find /home -type d); do
    if [[ -f "$D/.xscreensaver" ]]; then
        xscreensaverConfigs+=("$D/.xscreensaver")
    fi
done

for xscreensaverConfig in "${xscreensaverConfigs[@]}"; do
    sed -i "s/.*mode:.*/mode:\t\toff/g" "$xscreensaverConfig"
done

# Create the journal log directory, so that systemd logs are persisted
mkdir -p /var/log/journal