private-Device-Management/assets/hifiberry-alsactl.restore                  /etc/pi-top/.i2s-vol/
private-Device-Management/pt-device-manager/pt-device-manager               /usr/lib/pt-device-manager
private-Device-Management/pt-device-manager/ptdm*                           /usr/lib/pt-device-manager
private-Device-Management/shutdown/poweroff                                 /usr/lib/pt-device-manager
private-Device-Management/shutdown/poweroff-legacy                          /usr/lib/pt-device-manager
private-Device-Management/shutdown/pt-poweroff                              /usr/lib/pt-device-manager
private-Device-Management/shutdown/pt-reboot                                /usr/lib/pt-device-manager
