#!/bin/bash -e

case "$1" in
       try-restart)
       $0 status >/dev/null 2>&1 && $0 restart
       ;;

\
       triggered)
       # Try to restart pt-device-manager
       invoke-rc.d pt-device-manager try-restart || true
       exit 0
       ;;

       configure | abort-upgrade | abort-remove | abort-deconfigure)
       ;;

\
       *)
       echo "postinst called with unknown argument \`$1'" >&2
       exit 1
       ;;
esac

#DEBHELPER#

exit 0
