private-Device-Management/assets/hifiberry-alsactl.restore          /etc/pi-top/.i2s-vol/
private-Device-Management/tools/*                                   /usr/bin
private-Device-Management/pt-device-manager/pt-device-manager       /usr/lib/pt-device-manager
private-Device-Management/pt-device-manager/ptdm*                   /usr/lib/pt-device-manager
private-Device-Management/poweroff/poweroff                         /usr/lib/pt-device-manager
private-Device-Management/poweroff/poweroff-legacy                  /usr/lib/pt-device-manager
private-Device-Management/config                                    /usr/lib/pt-device-manager/
