#!/bin/bash -e

# Get current directory
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Create directory if it doesn't exist
sudo mkdir -p /etc/lightdm/lightdm.conf.d

# Copy xhost file to lightdm config directory
cp "${DIR}/pt-xhost-local-root.conf" /etc/lightdm/lightdm.conf.d/pt-xhost-local-root.conf
