#!/usr/bin/python3

from pitop.common.command_runner import run_command

from os.path import exists

try:
    device_version_file = "/etc/pi-top/pi-topd/device_version"

    if exists(device_version_file):

        device_version = ""
        with open(device_version_file, "r") as f:
            device_version = f.readline().strip()

        print(f"Device: {device_version}")
        if device_version in ["pi_top", "pi_top_ceed"]:
            run_command(
                "/usr/lib/pi-topd/poweroff-legacy",
                timeout=15
            )
        elif device_version in ["pi_top_3", "pi_top_4"]:
            run_command(
                f"/usr/lib/pi-topd/poweroff {device_version}",
                timeout=5
            )
        else:
            print("pt-poweroff did not receive a valid pt product version number.")
            exit(0)

except Exception as e:
    print("Error starting shutdown service: " + str(e))
