class DeviceInfo:
    ID__MCU_SOFT_VERS_MAJOR = 0xE0
    ID__MCU_SOFT_VERS_MINOR = 0xE1
    ID__SCH_REV_MAJOR = 0xE2
    ID__SCH_REV_MINOR = 0xE3
    ID__BRD_REV = 0xE4
    ID__PART_NAME = 0xE5
    ID__PART_NUMBER = 0xE6
    ID__SERIAL_ID = 0xE7
    ID__DISPLAY_MCU_SOFT_VERS_MAJOR = 0xE8
    ID__DISPLAY_MCU_SOFT_VERS_MINOR = 0xE9
    ID__DISPLAY_SCH_REV_MAJOR = 0xEA
    ID__DISPLAY_SCH_REV_MINOR = 0xEB
    ID__DISPLAY_BRD_REV = 0xEC
    ID__DISPLAY_PART_NAME = 0xED
    ID__DISPLAY_PART_NUMBER = 0xEE
    ID__DISPLAY_SERIAL_ID = 0xEF
