#!/usr/bin/python3

# For testing the zmq servers

import zmq
import time

zmq_context = zmq.Context()
zmq_socket = zmq_context.socket(zmq.REQ)

print ("Connecting...")
zmq_socket.connect("tcp://127.0.0.1:3782")
print ("OK.")

time.sleep(1)

for i in range(100):

	print ("Sending message...")
	
	zmq_socket.send_string("Test")

	print ("Waiting for response...")
	response = zmq_socket.recv_string()

	print ("Received: " + response)

	time.sleep(1)

print ("Closing socket...")

zmq_socket.close()

print ("Done.")

