#!/usr/bin/python

# The entry point for the application. Creates the controller and handles 
# high-level config e.g. debug level etc.

from ptdm_controller import ptdm_controller

debug_level = 0

controller = ptdm_controller(debug_level)
controller.start()