#!/usr/bin/python3

# For testing the zmq servers

import zmq
import time
from ptdm_message import Message


def test_request(test_name, message_request_id, parameters, expected_response_id, expected_response_parameters):
    print("Test " + test_name)
    message_string = Message.build_message_string(
        message_request_id, parameters)
    print("Sending:" + message_string)
    zmq_socket.send_string(message_string)
    response_string = zmq_socket.recv_string()
    print("Received response:" + response_string)

    response = Message(response_string)

    if (response.message_id() != expected_response_id):
        print("Test failed. Unexpected response: " + str(response.message_id()))
        return

    for i in range(len(expected_response_parameters)):
        if (expected_response_parameters[i] != response.parameters()[i]):
            print("Test failed. Unexpected response parameter. Expected: " + str(expected_response_parameters[i]) + ", got:" + str(response.parameters()[i]))
            return

    print("Test passed")


zmq_context = zmq.Context()
zmq_socket = zmq_context.socket(zmq.REQ)

print("Connecting...")
zmq_socket.connect("tcp://127.0.0.1:3782")
time.sleep(0.5)
print("OK.")

test_request("Set Brightness to 2", Message.REQ_SET_BRIGHTNESS, ["2"], Message.RSP_SET_BRIGHTNESS, [])
test_request("Get Brightness", Message.REQ_GET_BRIGHTNESS, [], Message.RSP_GET_BRIGHTNESS, ["2"])
test_request("Set Brightness to 10", Message.REQ_SET_BRIGHTNESS, ["10"], Message.RSP_SET_BRIGHTNESS, [])
test_request("Get Brightness", Message.REQ_GET_BRIGHTNESS, [], Message.RSP_GET_BRIGHTNESS, ["10"])
test_request("Get Device ID", Message.REQ_GET_DEVICE_ID, [], Message.RSP_GET_DEVICE_ID, ["2"])

print("Closing socket...")

zmq_socket.close()

print("Done.")
