#!/usr/bin/python3

# The entry point for the application. Creates the controller and handles 
# high-level config e.g. debug level etc.

import ptdm_controller

ptdm_controller.initialise()
ptdm_controller.run()

