#!/usr/bin/python3

# For testing the zmq servers

import zmq
import time
import ptdm_messages



zmq_context = zmq.Context()
zmq_socket = zmq_context.socket(zmq.REQ)

print ("Connecting...")
zmq_socket.connect("tcp://127.0.0.1:3782")
print ("OK.")

time.sleep(0.5)

print ("Testing REQ_PING...")
zmq_socket.send_string(str(ptdm_messages.REQ_PING))
message_id, parameters = ptdm_messages.parse_message(zmq_socket.recv_string())

if (message_id != ptdm_messages.RSP_PONG):
	print ("Unexpected response: " + str(message_id))
else:
	print ("OK")

time.sleep(0.1)

print ("Testing REQ_GET_HUB_INFO...")
zmq_socket.send_string(str(ptdm_messages.REQ_GET_HUB_INFO))
message_id, parameters = ptdm_messages.parse_message(zmq_socket.recv_string())

if (message_id != ptdm_messages.RSP_GET_HUB_INFO):
	print ("Unexpected response: " + str(message_id))
else:
	print ("OK")

time.sleep(0.1)

print ("Testing REQ_GET_BRIGHTNESS...")
zmq_socket.send_string(str(ptdm_messages.REQ_GET_BRIGHTNESS))
message_id, parameters = ptdm_messages.parse_message(zmq_socket.recv_string())

if (message_id != ptdm_messages.RSP_GET_BRIGHTNESS):
	print ("Unexpected response: " + str(message_id))
else:
	print ("OK")

time.sleep(0.1)

print ("Testing REQ_SET_BRIGHTNESS...")
zmq_socket.send_string(str(ptdm_messages.REQ_SET_BRIGHTNESS) + "|23")
message_id, parameters = ptdm_messages.parse_message(zmq_socket.recv_string())

if (message_id != ptdm_messages.RSP_SET_BRIGHTNESS):
	print ("Unexpected response: " + str(message_id))
else:
	print ("OK")

time.sleep(0.1)


print ("Closing socket...")

zmq_socket.close()

print ("Done.")

