#!/usr/bin/python3

from pitopcommon.command_runner import run_command

from os.path import exists

try:
    device_version_file = "/etc/pi-top/pt-device-manager/device_version"

    device_version = ""
    if exists(device_version_file):
        with open(device_version_file, "r") as f:
            device_version = f.readline()

        if device_version in ["pi_top", "pi_top_ceed"]:
            run_command(["/usr/lib/pt-device-manager/poweroff-legacy"])
        elif device_version in ["pi_top_3", "pi_top_4"]:
            run_command(
                [
                    "/usr/bin/python3",
                    "-B",
                    "/usr/lib/pt-device-manager/poweroff",
                    str(device_version),
                ]
            )
        else:
            print("pt-poweroff did not receive a valid pt product version number.")
            exit(0)

except Exception as e:
    print("Error starting shutdown service: " + str(e))
